name: CI
on: [push, pull_request]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
      - uses: actions/checkout@v3.1.0
      - run: python -m pip install --upgrade black
      - run: black --check .

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
      - uses: actions/checkout@v3.1.0
      - run: python -m pip install flake8
      - run: flake8

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
            python-version: 3.8
      - uses: actions/checkout@v3.1.0
      - run: python -m pip install cryptography isort==5.6.4
      - run: isort --diff --check lora tests

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3.1.0
      - run: python -m pip install discover cryptography==3.2
      - run: discover
